### ISSUE TITLE
scroll-area for time picker

### ISSUE THREAD

**Issue by iamsatyajit05** [rudrodip/shadcn-date-time-picker#1]
A scroll-area for the time picker would be a good choice because the default scrollbar isn't visually appealing.

With Default
![image](https://github.com/user-attachments/assets/14008916-19f6-482a-8870-fb605ec984eb)

With Scroll-area (I had hovered over the hour selection)
![image](https://github.com/user-attachments/assets/48839271-eaef-44f0-8e68-192df8aa5bc0)

**Comment by rudrodip** [comment]
open a pull request if you've changed
